### ISSUE TITLE
How to generate multiple distinct paths between rooms?

### ISSUE THREAD

**Issue by masonwheeler** [Chris3606/GoRogue#21]
If you generate a set of rooms with the `RandomRoomsGenerator`, and then use a standard connector to connect them, you'll end up with a system where, if understood as a graph where each room is a node and each corridor is an edge, the graph is purely acyclic.  (ie. there's only one path between any two given rooms, and if you .)

If you try to run a connector again, it will detect that the entire area is one big region and there's nothing that needs to be connected.

In popular roguelikes such as ADOM and NetHack, the room graph is not acyclic; most levels contain multiple ways to get between certain rooms.  This makes the levels generated here look weird.

Is there any simple way to create cyclic paths among the rooms generated?  Right now, the only good alternatives I can think of involves something convoluted like generating a room set, cloning it, applying a different corridor generator to each copy, and then ORing them together, and that just seems messy...

**Comment by Chris3606** [comment]
First, I'm typing this on a phone so apologies in advance for any mistakes.

This depends on the connector you use. If you use ClosestAreaConnector, then there isn't an exceedingly straightforward way to do so, because by definition that connection algorithm connects each room to only it's closest counterpart that isn't part of the whole (creating a minimum spanning tree, if the map is interpreted as a graph).

OrderedMapAreaConnector, however, could be used to create cyclic paths. It provides two Connect overloads; one that uses a MapAreaFinder to determine areas to connect (and thus suffers from the problem you describe), and one that instead takes a ReadOnlyList which specifies the areas to connect, in the order to connect them (it connects index 0 to index 1, 1 to 2, etc). I believe this version could be used to achieve the effect you are looking for. A very basic example:

```C#
// Generate map, without connecting it
RandomRoomsGenerator.Connect(map, x, y, z, a, connectUsingDefault: false);

// Find map areas before we connect
var areas = MapAreaFinder.FindAreasFor(map, AdjacencyRule.CARDINALS).ToList(); // GoRogue extension method ToList

// Connect each room to 2 others
for (int i =0; i < 2; i++)
{
    // GoRogue extension method, shuffle list order
    // so we connect each room to a random one
    areas.FisherYatesShuffle();

    // Connect areas
    OrderedMapAreaConnector.Connect(map, areas);
}
```

Thanks! Feel free to let me know if that's what you need, and/or any suggestions to make it easier.  The map Glgeneration architecture isn't fully developed currently, and I'm not sure I'll happy with all of it as it stands, so suggestions are welcome 😁.

**Comment by masonwheeler** [comment]
Interesting.  I'll have to look at `OrderedMapAreaConnector`.

> `// GoRogue extension method ToList`

OK, I have to ask.  What's the deal with this?  `System.Linq.Enumerable` already provides the exact same functionality with the exact same name, and it can conflict with it when `GoRogue` and `System.Linq` are both in your `using` list.

**Comment by Chris3606** [comment]
I was reminded of this myself as I was writing that example.  Likely reason is being way too tired to remember linq had it when I was writing it to be honest... I'll be putting an issue up about it tonight 😁

**Comment by Chris3606** [comment]
For the sake of resolving the issue, did this method end up working for your needs?

**Comment by masonwheeler** [comment]
Yes, that produces a very different dungeon look.  Thanks!
