### ISSUE TITLE
EventHandlers and layers memory high memory usage

### ISSUE THREAD

**Issue by tgiachi** [Chris3606/GoRogue#298]
HI! I'm using your library for a rouguelike 2d mmorg (https://github.com/tgiachi/DarkStar).

I'm creating a world with about 20 maps of 40x40 size and it's consuming a lot of memory (about 1.5Gb). Digging deeper, I noticed that the objects that take up a lot of memory are of type `
System.EventHandler<ValueChangedEventArgs<Boolean>>`. My question is: is it possible to mask and/or drop the event handlers for a single map layer? (in my case Terrain ?) Thank you! the version of lib is 3.0.0-beta02

**Comment by Chris3606** [comment]
Hi!

I'll have to look at the memory usage in more detail to be sure, as I don't fully understand the use case in which allocations should be dominated by event arguments such as these.  The primary places where `ValueChangedEventArgs<bool>` is used revolve around the `IGameObject.WalkabilityChanging` and `WalkabilityChanged` events, and the corresponding `TransparencyChanging` and `TransparencyChanged` events.  By default, for each item there is one handler attached to the `WalkabilityChanged` event (by the map), one handler attached to the `TransparencyChanged` event, and one handler attached to the `TransparencyChanging` event.

Any of the aforementioned changing/changed events are not fired unless walkability or transparency actually changes, so it seems unlikely that this is a result of repeated `ValueChangedEventArgs` allocations (and that should cause allocation, not constant memory usage, even if it was so).  And there really shouldn't be a situation where single handlers that aren't ever actually fired add up to this kind of memory usage, so I'm a bit puzzled.  In short, no there's not a way to drop the event handlers, because this behavior sounds like a bug and if the bug didn't exist, dropping them wouldn't be necessary :D.

One thing you might try, is when you create your maps, pass `useCachedGridViews = false` to the constructor.  This will slow down quite a few operations of the map, but it disables a lot of the event handlers I'm discussing above, so it would at least be a good test to validate those are actually what is causing the issue.

**Comment by Chris3606** [comment]
Edit: sorry, I misread the GoRogue version you were using.  The flag I mentioned was introduced in beta4; and the behavior prior to that version is the behavior you get with the flag set to false in beta4; this actually makes those event handlers taking up so much memory even more puzzling, since they practically aren't used by default prior to beta4.

Quite a bit changed in terms of how some object event handlers are used between beta2 and beta4; I'll run some tests across versions to see if I can spot anything amiss.

**Comment by Chris3606** [comment]
@tgiachi  I did some more work on this, but still can't replicate something like what you're seeing in an isolated example.  If you're still experiencing this issue, any additional information would be appreciated.

**Comment by tgiachi** [comment]
Hello and thank you for analyzing the problem!
In these days I'm doing some tests and I'll give you an example to be able to replicate the problem!

**Comment by Chris3606** [comment]
I have no ability to replicate this on this end with modern v3 betas; so I'm going to close this for now.  If it does prove to pop up again, feel free to re-open.
