### ISSUE TITLE
Lines

### ISSUE THREAD

**Issue by bloodyraoul** [Chris3606/GoRogue#37]
The list of coords returned by Lines.Get(start, end) should be ordered from start to end instead of ordered in ascending order or maybe it could be an option
thanks

**Comment by Chris3606** [comment]
It should already be in start to finish order -- I'll look into this.

**Comment by Chris3606** [comment]
Apologies this has taken so long, the last couple weeks have been very hectic irl.  I should have time to sit at a dev-capable computer to take a look at this later this week.

I do want to ask, just for clarification -- in your case, you found that the coordinates returned by `Lines.Get` were _not_ in order from start to finish?  Which line generation algorithm were you using when this occurred?

**Comment by bloodyraoul** [comment]
Hey,
What I remember, it was a line from bottom to top (10,10) to 3,3) for example) and it was ordened from (3,3). I will test it more to try to have more informations

**Comment by Chris3606** [comment]
I"ve been able to replicate this -- it is an issue with only Bresenham's in particular.  This is because, in my bresenham's implementation, I am using `yield return` to return each point as it is found, which doesn't allow me to reverse the order of the returned values in the case that I switched the start and end points to begin with (in order to allow the algorithm to function properly).  

I was actually aware of this once upon a time, but sadly had long forgotten about it since I failed to make an issue for it.  I'll look into fixing this -- easy to fix, possibly more difficult to fix without sacrificing performance.  In the meantime, using the DDA line generation algorithm (`Lines.Algorithm.DDA`) will produce a very similar (usually identical) line, with similar speed, but without the issue.

Thanks!

THanks

**Comment by bloodyraoul** [comment]
It works well with DDA, so i will use it
thank you ;)

**Comment by Chris3606** [comment]
A version of Bresenham's with the points ordered is now on the develop branch (and will be released shortly with 1.4).  However, it can be a bit slower, so I'd recommend sticking with DDA for ordered points unless there is a reason not to.  Thanks!
