### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by nightblade9** [Chris3606/GoRogue#47]
Hi,

I just learned about your project yesterday so apologies if this is a dumb/answered question.

I'm working with .NET core, and the [wiki page for RLNET project setup](https://github.com/Chris3606/GoRogue/wiki/RLNET-Project-Setup) suggests:

>  Furthermore, although it is possible to recompile RLNET to work with a .NET Core project, [...]

This seems a little misleading. It looks like RLNET (aside from being a "dead" project with the last commit circa 2016) depends on OpenTK. From what I can surmise from [this issue regarding OpenTK support of .NET Core](https://github.com/opentk/opentk/issues/245), this is something that will happen in the upcoming (OpenTK 4.0?) release.

Meanwhile, some generous person created [an OpenTK .NET Core nuget package here](https://www.nuget.org/packages/OpenTK.NETCore/). While not official in any way, I'm guessing it works.

Piecing this all together, I can assume that someone tested GoRogue with a custom build of RLNET that uses the above-mentioned package of OpenTK on .NET Core.

Assuming that's true, would it be possible to put together some sort of package (eg. zip file, starter project) that links all these things together? I really don't want to build RLNET from scratch (especially since it looks abandoned), and if I can link some version of GoRogue that uses the homebrew version of OpenTK on .NET Core today, but switches to the official OpenTK 4.0 once it's released and stable (without having to recompile by hand), that would save a lot of effort.

Or is my entire premise wrong, and .NET Core isn't really supported with GoRogue today?

**Comment by TimyJ** [comment]
GoRogue is definitely .NetCore.  the wiki is pretty out of date(because I'm lazy and take up all of his time) as far as rlnet goes I know he got it working with core(I think) and wouldn't be terribly hard to host a starter package. Personally Sadconsole would be my choice if you wanted to get going. But we are rolling our own with monogame and it hasn't been hard to setup. He's a work so will be a while before you get a complete and better informed answer but wanted to shoot you something in the meantime. Thanks for using GoRogue!

**Comment by nightblade9** [comment]
That pretty much answers my query. It is clear now that drawing isn't part of GoRogue (although admittedly I didn't notice a lack of drawing in the `README`/Wiki).

I'll try SadConsole with GoRogue on .NET Core and report back if I find any problems. For now, all I can suggest is updating the `README` and/or wiki with an easier "quick start" example for someone like me (looking for a "complete" roguelike solution).

**Comment by Chris3606** [comment]
No problem. I know GoRogue works with SadConsole. What I'm not sure about is whether SadConsole works with .NET Core - I tested it with a .NET Framework project. I know SadConsole uses MonoGame, and MonoGame on .net core is in relatively early stages.

At any rate, I'm certainly curious to see how it goes!

**Comment by Thraka** [comment]
I used GoRogue with SadConsole in my "in progres" roguelike tutorial. No problems, GoRogue is highly portable. The only thing you end up working around are primitive types that both GoRogue and Monogame define, such as points and rectangles. SadConsole and GoRogue also define some things similar too, such as a direction type.

It's quite possible that I would strip this stuff out of SadConsole and tell people to just use GoRogue for that stuff. I would then probably make a translation library for easy-of-use between the two.

GoRogue is amazing!

**Comment by Chris3606** [comment]
@Thraka I am glad to hear you ended up using GoRogue!  Having the SadConsole tutorial, when it's complete, using GoRogue will likely be as good for GoRogue as it is for SadConsole -- I know GoRogue definitely needs an example game to lean on.

Regarding the potential for removing some duplicate items from SadConsole and providing a translation library - I had considered myself coming up with a translation library for SadConsole, just hadn't gotten around to it, due to time and me not being a 100% expert in SadConsole.

If you do end up deciding to proceed down that path, and you find anything on the GoRogue side that is difficult to work with or integrate, or some things that are missing that make integration difficult to accomplish, please feel free to let me know -- I'd certainly like to see if a tweak or addition to GoRogue could help out.

Thanks!

**Comment by nightblade9** [comment]
For posterity: I can confirm that this stack works in entirety on .NET Core. If anyone wants to know how to set this up in the future:

- Download the [SadConsole .NET Core sample app](https://github.com/Thraka/SadConsole/issues/137#issuecomment-406364890)
- Delete whatever you don't need
- In the main application `.csproj` file, add a reference to GoRogue: `<PackageReference Include="GoRogue" Version="1.4.4" />` (`1.4.4` is the latest release as of now).
- Run your app

It runs! I didn't see the `GoRogue.dll` file in `bin\Debug` for some reason, so I published the app (`dotnet publish ...`) and verified that I can see the DLL in the output.

Yay!
