### ISSUE TITLE
Common interface for Flee/GoalMap

### ISSUE THREAD

**Issue by tstavrianos** [Chris3606/GoRogue#69]
Since FleeMap, GoalMap and WeightedGoalMap all implement IMapView<double?>, won't it be better to create a IGoalMap interface that extends IMapView<double?> and use that instead?

With a new base interface, you can then easily add a function that uses the underlying map's data to figure out the best direction from a given position (sth like: Direction GetDirection(Coord pos) ) that goes through all the neighbors to the given coord and returns the direction with the highest score.

**Comment by Chris3606** [comment]
I definately can add a function like the one you described.  I'm not sure an actual common interface is necessary (since all implementations of the interface would have to implement the function (and the implementation is universally the same because all it needs is the `IMapView<double?>` functions.  Then again, I've used extension methods to work in default (universal) methods to `IMapView`, so I might be able to do the same with a common interface for goal maps.  Thanks!
