### ISSUE TITLE
MazeGenerator.Generate does not contain an overload that omits rng

### ISSUE THREAD

**Issue by Thraka** [Chris3606/GoRogue#79]
`RoomsGenerator.Generate` and `Connectors.RoomDoorConnector.ConnectRooms` contain an overload where you can omit the rng parameter (even though default is null) but `MazeGenerator.Generate` does not. I would make them all match one way or the other.

**Comment by Chris3606** [comment]
I can merge in the pr that fixes it if you want, but it actually does contain such an oveload already, as rng is an optional parameter I'm the current implementation 😁. If this isn't obvious enough though, maybe it's worth adding the overload anyway, or at least modifying the documentation in some way?

**Comment by Thraka** [comment]
Yes that is true :) However, the only reason I brought it up was the the other gen methods you added from my other PR have these two overloads where it points to passing in null. So I was just matching them up behavior wise 😄

**Comment by Chris3606** [comment]
I'll probably go ahead and merge the PR, if nothing else it makes it more obvious.  The only reason I originally used default parameters for that one, and overloads for the other, is because I wanted to preserve the order of the first two arguments -- all the generators take a map then an RNG first, how I have it arranged.  Since some of the components after the RNG are not optional (by design), I used overloads to create that effect.

In any case, all it does is add one overload, so not a huge deal to add in.

**Comment by Thraka** [comment]
I always wonder if methods like this work better with some sort of CreationParameters type of object, like you have on Process.Start. I hate methods with tons of parameters 😄

**Comment by Chris3606** [comment]
I had considered this myself.  The reason I didn't originally (when I started work on the library years ago) is that, at the time, it was more work for a user to have to `new MyParametersObject(...)` and then pass them.  With as far as structs and struct initialization syntax has come in C#, it's been a consideration to do for GoRogue 2.0... There are a few spots where such syntax could be used.  The question becomes what is the cutoff for number of acceptable parameters, and trying to keep the interfaces consistent -- take map gen for example -- if one algorithm uses that method, they all probably should...

**Comment by Thraka** [comment]
I hate both solutions.. I hate creation params, and I hate crazy long methods :) Oh well lol
